# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 953090617e5bc24e7164e3e66c3384fc36204284756da251ecbfb173f8fcc2b7d542dd5088bc32276adf9b7590f403ffebba7c69fcb4c7d556dd4401d2f390a1

test:
  secret_key_base: c05c1726c6cbec3df810aea647c17e48c5c48e250454fca8612f10f800bf8aaba392420f05405feddd3070709c9bae528c8e35e4cc34284237bef10f8a32c23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
